name: Builds the game and upload it to itch.io

on:
  push:
    branches:
      - master

env:
  GRADLE_USER_HOME: .gradle
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gradle cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          path: |
            .gradle/wrapper
            .gradle/caches

      - name: Setup jdk cache
        uses: actions/cache@v2
        id: jdkcache
        with:
          key: ${{ runner.os }}-jdk-${{ hashFiles('**/build.gradle') }}
          path: |
            jdk.tar.gz

      - name: Download JDK
        if: steps.jdkcache.outputs.cache-hit != 'true'
        run: wget https://download.bell-sw.com/java/14.0.1+8/bellsoft-jdk14.0.1+8-linux-amd64-full.tar.gz -O jdk.tar.gz

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          jdkFile: jdk.tar.gz



      - name: Download butler
        run: wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O butler.zip

      - name: Unzip buttler
        run: unzip butler.zip



      - name: Fix permissions
        run: chmod +x butler && chmod +x gradlew



      - name: Build jar
        run: ./gradlew lwjgl3:jar

      - name: Build gwt
        run: ./gradlew html:dist

      - name: Build package image
        run: ./gradlew lwjgl3:jpackageImage

      - name: Build deb/rpm
        run: ./gradlew lwjgl3:jpackage

      - name: Fix file names
        run: mv lwjgl3/build/lib/*.jar OnGuard_linux.jar && mv lwjgl3/build/jpackage/*.deb OnGuard.deb && mv lwjgl3/build/jpackage/*.rpm OnGuard.rpm



      - name: Check if butler works
        run: ./butler -V

      - run: ./butler push OnGuard_linux.jar lyze237/on-guard:linux-jar

      - run: ./butler push lwjgl3/build/jpackage/OnGuard lyze237/on-guard:linux-image

      - run: ./butler push OnGuard.deb lyze237/on-guard:linux-deb
      - run: ./butler push OnGuard.rpm lyze237/on-guard:linux-rpm

      - run: ./butler push html/build/dist lyze237/on-guard:html




  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gradle cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          path: |
            .gradle/wrapper
            .gradle/caches

      - name: Setup jdk cache
        uses: actions/cache@v2
        id: jdkcache
        with:
          key: ${{ runner.os }}-jdk-${{ hashFiles('**/build.gradle') }}
          path: |
            jdk.zip

      - name: Download JDK
        if: steps.jdkcache.outputs.cache-hit != 'true'
        run: Invoke-WebRequest -Uri https://download.bell-sw.com/java/14.0.1+8/bellsoft-jdk14.0.1+8-windows-amd64-full.zip -OutFile jdk.zip

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          jdkFile: jdk.zip



      - name: Download Butler
        run: Invoke-WebRequest -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -OutFile butler.zip

      - name: Extract butler
        run: Expand-Archive -DestinationPath . butler.zip



      - name: Build jar
        run: ./gradlew.bat lwjgl3:jar

      - name: Build package image
        run: ./gradlew.bat lwjgl3:jpackageImage

      - name: Build exe/msi
        run: ./gradlew.bat lwjgl3:jpackage

      - name: Fix file names
        run: mv lwjgl3/build/lib/*.jar OnGuard_windows.jar && mv lwjgl3/build/jpackage/*.exe OnGuard.exe && mv lwjgl3/build/jpackage/*.msi OnGuard.msi



      - name: Check if butler works
        run: ./butler.exe -V

      - run: ./butler push OnGuard_windows.jar lyze237/on-guard:windows-jar

      - run: ./butler push lwjgl3/build/jpackage/OnGuard lyze237/on-guard:windows-image

      - run: ./butler push OnGuard.exe lyze237/on-guard:windows-exe
      - run: ./butler push OnGuard.msi lyze237/on-guard:windows-msi

